import { describe, expect, it } from "vitest";
import { parse } from "yaml";
import type { ServiceDefinition } from "../src/config/types.js";
import type { EnvironmentPlan } from "../src/graph/resolver.js";
import { renderComposeFile } from "../src/backends/compose-spec.js";

function plan(
  services: Record<string, ServiceDefinition>,
  envVars: EnvironmentPlan["env"] = {},
): EnvironmentPlan {
  return {
    name: "market",
    file: "market.ts",
    env: envVars,
    dependsOn: [],
    order: [],
    waves: [],
    services,
  };
}

describe("renderComposeFile (compose)", () => {
  const yaml = renderComposeFile(
    plan(
      {
        web: {
          image: "nginx",
          ports: ["8080:80"],
          dependsOn: ["api"],
          restart: "always",
          env: { TOKEN: { $secret: "API_TOKEN" } },
        },
        api: { image: "api", replicas: 2 },
      },
      { LOG: "info" },
    ),
    { swarm: false, baseEnv: { GLOBAL: "g" }, targetEnv: {} },
  );
  const doc = parse(yaml);

  it("emits a do-not-edit header", () => {
    expect(yaml.startsWith("# Generated by kaupang")).toBe(true);
  });

  it("renders image, ports, depends_on and restart", () => {
    expect(doc.services.web.image).toBe("nginx");
    expect(doc.services.web.ports).toEqual(["8080:80"]);
    expect(doc.services.web.depends_on).toEqual(["api"]);
    expect(doc.services.web.restart).toBe("always");
  });

  it("merges base/env over the service and renders secrets as refs", () => {
    expect(doc.services.web.environment.GLOBAL).toBe("g");
    expect(doc.services.web.environment.LOG).toBe("info");
    expect(doc.services.web.environment.TOKEN).toBe("${API_TOKEN}");
  });

  it("uses deploy.replicas for replica counts", () => {
    expect(doc.services.api.deploy.replicas).toBe(2);
  });

  it("never writes a secret value or marker into the file", () => {
    expect(yaml).not.toContain("$secret");
  });
});

describe("renderComposeFile (swarm)", () => {
  const yaml = renderComposeFile(
    plan({
      web: {
        image: "nginx",
        dependsOn: ["api"],
        restart: "on-failure",
        replicas: 3,
        pull: "always",
      },
    }),
    { swarm: true, baseEnv: {}, targetEnv: {} },
  );
  const doc = parse(yaml);

  it("moves replicas and restart under the deploy key", () => {
    expect(doc.services.web.deploy.replicas).toBe(3);
    expect(doc.services.web.deploy.restart_policy.condition).toBe("on-failure");
  });

  it("drops depends_on and pull_policy (unsupported in swarm)", () => {
    expect(doc.services.web.depends_on).toBeUndefined();
    expect(doc.services.web.pull_policy).toBeUndefined();
  });

  it("maps restart policies to swarm conditions", () => {
    const none = parse(
      renderComposeFile(plan({ s: { image: "x", restart: "no" } }), {
        swarm: true,
        baseEnv: {},
        targetEnv: {},
      }),
    );
    expect(none.services.s.deploy.restart_policy.condition).toBe("none");

    const any = parse(
      renderComposeFile(plan({ s: { image: "x", restart: "unless-stopped" } }), {
        swarm: true,
        baseEnv: {},
        targetEnv: {},
      }),
    );
    expect(any.services.s.deploy.restart_policy.condition).toBe("any");
  });
});

describe("renderComposeFile build contexts", () => {
  it("emits build alongside the image tag it produces", () => {
    const doc = parse(
      renderComposeFile(plan({ web: { build: "./services/api", image: "ghcr.io/acme/api" } }), {
        swarm: false,
        baseEnv: {},
        targetEnv: {},
      }),
    );
    expect(doc.services.web.build).toBe("./services/api");
    expect(doc.services.web.image).toBe("ghcr.io/acme/api");
  });
});

describe("renderComposeFile run-once dependencies", () => {
  it("gates dependents on a run-once job's successful exit", () => {
    const doc = parse(
      renderComposeFile(
        plan({
          migrate: { image: "app", runOnce: true },
          web: { image: "app", dependsOn: ["migrate"] },
        }),
        { swarm: false, baseEnv: {}, targetEnv: {} },
      ),
    );
    expect(doc.services.web.depends_on).toEqual({
      migrate: { condition: "service_completed_successfully" },
    });
    // run-once jobs are forced to restart "no" so they actually complete
    expect(doc.services.migrate.restart).toBe("no");
  });

  it("mixes conditions when only some deps run once", () => {
    const doc = parse(
      renderComposeFile(
        plan({
          migrate: { image: "app", runOnce: true },
          cache: { image: "redis" },
          web: { image: "app", dependsOn: ["migrate", "cache"] },
        }),
        { swarm: false, baseEnv: {}, targetEnv: {} },
      ),
    );
    expect(doc.services.web.depends_on).toEqual({
      migrate: { condition: "service_completed_successfully" },
      cache: { condition: "service_started" },
    });
  });

  it("keeps short-form depends_on when nothing runs once", () => {
    const doc = parse(
      renderComposeFile(
        plan({ a: { image: "x" }, b: { image: "x", dependsOn: ["a"] } }),
        { swarm: false, baseEnv: {}, targetEnv: {} },
      ),
    );
    expect(doc.services.b.depends_on).toEqual(["a"]);
  });
});

describe("renderComposeFile network/volume collection", () => {
  const yaml = renderComposeFile(
    plan({
      web: {
        image: "x",
        networks: ["frontend"],
        volumes: ["data:/var/lib", "./local:/app", "/abs:/x"],
      },
    }),
    { swarm: false, baseEnv: {}, targetEnv: {} },
  );
  const doc = parse(yaml);

  it("declares referenced networks at the top level", () => {
    expect(doc.networks).toEqual({ frontend: {} });
  });

  it("declares only named volumes (not bind mounts)", () => {
    expect(doc.volumes).toEqual({ data: {} });
  });
});

describe("renderComposeFile network aliases", () => {
  it("renders the map form with aliases and still declares the network", () => {
    const doc = parse(
      renderComposeFile(
        plan({ web: { image: "x", networks: { frontend: { aliases: ["api.internal"] } } } }),
        { swarm: false, baseEnv: {}, targetEnv: {} },
      ),
    );
    expect(doc.services.web.networks).toEqual({ frontend: { aliases: ["api.internal"] } });
    expect(doc.networks).toEqual({ frontend: {} });
  });

  it("still supports the plain list form", () => {
    const doc = parse(
      renderComposeFile(plan({ web: { image: "x", networks: ["backend"] } }), {
        swarm: false,
        baseEnv: {},
        targetEnv: {},
      }),
    );
    expect(doc.services.web.networks).toEqual(["backend"]);
    expect(doc.networks).toEqual({ backend: {} });
  });
});
