import { join } from "node:path";
import { stringify } from "yaml";
import { k8sName, stackName } from "../util/names.js";
import { isSecret, mergeEnv } from "../util/env.js";
import type { EnvMap, ServiceDefinition } from "../config/types.js";
import type { EnvironmentPlan } from "../graph/resolver.js";
import type { Backend, BackendContext, MaterializedEnvironment } from "./types.js";

/**
 * Minimal-but-functional Kubernetes translation: one Namespace, and a
 * Deployment (+ Service when ports are declared) per service. Build contexts
 * are not supported here — provide prebuilt `image`s for the kubernetes backend.
 */
export const kubernetesBackend: Backend = {
  name: "kubernetes",
  materialize(env, ctx): MaterializedEnvironment {
    const namespace = k8sName(stackName(ctx.project, env.name));
    const docs: unknown[] = [
      {
        apiVersion: "v1",
        kind: "Namespace",
        metadata: { name: namespace, labels: { "app.kubernetes.io/managed-by": "kaupang" } },
      },
    ];

    for (const [name, def] of Object.entries(env.services)) {
      docs.push(deployment(name, def, namespace, ctx, env.env));
      if (def.ports?.length) docs.push(service(name, def, namespace));
    }

    const file = join(ctx.cacheDir, namespace, "manifest.yaml");
    const content = docs.map((d) => stringify(d)).join("---\n");

    return {
      files: [{ path: file, content: `# Generated by kaupang\n${content}` }],
      up: [
        {
          description: `kubectl apply (${namespace})`,
          file: "kubectl",
          args: ["apply", "-f", file],
        },
      ],
      down: [
        {
          description: `kubectl delete namespace ${namespace}`,
          file: "kubectl",
          args: ["delete", "namespace", namespace, "--ignore-not-found"],
        },
      ],
      build: [],
    };
  },
};

function deployment(
  name: string,
  def: ServiceDefinition,
  namespace: string,
  ctx: BackendContext,
  envVars: EnvMap,
): unknown {
  if (!def.image) {
    throw new Error(
      `Service "${name}" needs an "image" for the kubernetes backend (build contexts are not supported).`,
    );
  }
  const appName = k8sName(name);
  const env = mergeEnv(ctx.baseEnv, envVars, ctx.targetEnv, def.env);
  // Secrets reference an externally-managed Secret so values never enter the manifest.
  const secretName = `${k8sName(ctx.project)}-secrets`;
  const container: Record<string, unknown> = {
    name: appName,
    image: def.image,
  };
  if (def.command) {
    container.command = Array.isArray(def.command) ? def.command : ["sh", "-c", def.command];
  }
  if (def.ports?.length) {
    container.ports = def.ports.map((p) => ({ containerPort: containerPort(p) }));
  }
  if (Object.keys(env).length) {
    container.env = Object.entries(env).map(([k, v]) =>
      isSecret(v)
        ? { name: k, valueFrom: { secretKeyRef: { name: secretName, key: v.$secret } } }
        : { name: k, value: v },
    );
  }

  return {
    apiVersion: "apps/v1",
    kind: "Deployment",
    metadata: { name: appName, namespace, labels: { app: appName } },
    spec: {
      replicas: def.replicas ?? 1,
      selector: { matchLabels: { app: appName } },
      template: {
        metadata: { labels: { app: appName } },
        spec: { containers: [container] },
      },
    },
  };
}

function service(name: string, def: ServiceDefinition, namespace: string): unknown {
  const appName = k8sName(name);
  return {
    apiVersion: "v1",
    kind: "Service",
    metadata: { name: appName, namespace },
    spec: {
      selector: { app: appName },
      ports: (def.ports ?? []).map((p) => {
        const target = containerPort(p);
        return { port: hostPort(p) ?? target, targetPort: target };
      }),
    },
  };
}

/** "8080:80" -> 80 (container side); "80" -> 80. */
function containerPort(p: string): number {
  const parts = p.split(":");
  return Number(parts.at(-1));
}

/** "8080:80" -> 8080; "80" -> undefined. */
function hostPort(p: string): number | undefined {
  const parts = p.split(":");
  return parts.length > 1 ? Number(parts[0]) : undefined;
}
