import { stringify } from "yaml";
import type { EnvMap, ServiceDefinition } from "../config/types.js";
import type { EnvironmentPlan } from "../graph/resolver.js";
import { mergeEnv, renderComposeEnv } from "../util/env.js";

interface ComposeOptions {
  /** Swarm uses the `deploy` key for replicas/restart and ignores depends_on. */
  swarm: boolean;
  baseEnv: EnvMap;
  targetEnv: EnvMap;
}

/** Render a docker-compose / stack YAML file from an environment plan. */
export function renderComposeFile(
  env: EnvironmentPlan,
  opts: ComposeOptions,
): string {
  // Services marked `runOnce` are run-to-completion jobs; dependents wait on
  // their successful exit instead of just their start.
  const completing = new Set(
    Object.entries(env.services)
      .filter(([, def]) => def.runOnce)
      .map(([name]) => name),
  );

  const services: Record<string, unknown> = {};
  for (const [name, def] of Object.entries(env.services)) {
    services[name] = toComposeService(def, opts, env.env, completing);
  }

  const spec: Record<string, unknown> = { services };

  const networks = collectNetworks(env);
  if (networks.length) {
    spec.networks = Object.fromEntries(networks.map((n) => [n, {}]));
  }
  const volumes = collectVolumes(env);
  if (volumes.length) {
    spec.volumes = Object.fromEntries(volumes.map((v) => [v, {}]));
  }

  return `# Generated by kaupang — do not edit by hand.\n${stringify(spec)}`;
}

function toComposeService(
  def: ServiceDefinition,
  opts: ComposeOptions,
  envVars: EnvMap,
  completing: Set<string>,
): Record<string, unknown> {
  const svc: Record<string, unknown> = {};

  if (def.image) svc.image = def.image;
  if (def.build) svc.build = def.build;
  if (def.command) svc.command = def.command;
  if (def.ports?.length) svc.ports = def.ports;
  if (def.volumes?.length) svc.volumes = def.volumes;
  if (def.networks?.length) svc.networks = def.networks;
  if (def.capAdd?.length) svc.cap_add = def.capAdd;
  if (def.entrypoint) svc.entrypoint = def.entrypoint;
  if (def.workingDirectory) svc.working_dir = def.workingDirectory;
  if (def.labels) svc.labels = def.labels;

  if (def.pull && !opts.swarm) svc.pull_policy = def.pull;

  const merged = mergeEnv(opts.baseEnv, envVars, opts.targetEnv, def.env);
  const environment = renderComposeEnv(merged);
  if (Object.keys(environment).length) svc.environment = environment;

  if (def.healthcheck) {
    svc.healthcheck = {
      test: def.healthcheck.test,
      interval: def.healthcheck.interval,
      timeout: def.healthcheck.timeout,
      retries: def.healthcheck.retries,
      start_period: def.healthcheck.startPeriod,
    };
  }

  // A run-once job must not restart, or it never completes.
  const restart = def.runOnce ? "no" : def.restart;

  if (opts.swarm) {
    // Swarm ignores top-level depends_on / restart; use the deploy key instead.
    const deploy: Record<string, unknown> = {};
    if (def.replicas != null) deploy.replicas = def.replicas;
    if (restart) deploy.restart_policy = { condition: toSwarmCondition(restart) };
    if (Object.keys(deploy).length) svc.deploy = deploy;
  } else {
    if (def.dependsOn?.length) svc.depends_on = renderDependsOn(def.dependsOn, completing);
    if (restart) svc.restart = restart;
    if (def.replicas != null) svc.deploy = { replicas: def.replicas };
  }

  return svc;
}

/**
 * Short-form `depends_on` (a list) unless a dependency is a completing job, in
 * which case use the long form so dependents wait for its successful exit.
 */
function renderDependsOn(
  deps: string[],
  completing: Set<string>,
): string[] | Record<string, { condition: string }> {
  if (!deps.some((d) => completing.has(d))) return deps;
  return Object.fromEntries(
    deps.map((d) => [
      d,
      { condition: completing.has(d) ? "service_completed_successfully" : "service_started" },
    ]),
  );
}

function toSwarmCondition(restart: NonNullable<ServiceDefinition["restart"]>): string {
  switch (restart) {
    case "no":
      return "none";
    case "on-failure":
      return "on-failure";
    default:
      return "any";
  }
}

function collectNetworks(env: EnvironmentPlan): string[] {
  const set = new Set<string>();
  for (const svc of Object.values(env.services)) {
    for (const n of svc.networks ?? []) set.add(n);
  }
  return [...set];
}

function collectVolumes(env: EnvironmentPlan): string[] {
  const set = new Set<string>();
  for (const svc of Object.values(env.services)) {
    for (const v of svc.volumes ?? []) {
      const source = v.split(":")[0]!;
      // Only named volumes (not bind mounts / absolute or relative paths).
      if (source && !source.includes("/") && !source.includes(".")) set.add(source);
    }
  }
  return [...set];
}
